[[pages]]
path = "pages/home.py"
name = "Previsões"
icon = "📊"

[[pages]]
path = "pages/historico.py"
name = "Histórico"
icon = "🗂️"
url_path = "historico"

[[pages]]
path = "pages/estatisticas.py"
name = "Estatísticas"
icon = "🎯"
url_path = "estatisticas"

[[pages]]
path = "pages/upload.py"
name = "Upload"
icon = "📤"
url_path = "upload"

[[pages]]
path = "pages/configuracoes.py"
name = "Configurações"
icon = "⚙️"
url_path = "configuracoes"

[[pages]]
path = "pages/benchmark.py"
name = "Benchmark"
icon = "🥇"
url_path = "benchmark"
